# Languages

en:
  label: English
  weight: 1
  locale: en-us
  contentDir: content/en
  menu:
    main:
      - name: About me
        url: /authors/me/
        weight: 10

      - name: Posts
        url: /blog/
        weight: 20

      - name: Projects
        url: /projects/
        weight: 30

ru:
  label: Русский
  weight: 2
  locale: ru-RU
  contentDir: content/ru
  menu:
    main:
      - name: Обо мне
        url: /authors/me/
        weight: 10

      - name: Публикации
        url: /blog/
        weight: 20

      - name: Проекты
        url: /projects/
        weight: 30